spring:
  profiles:
    active: dev
  application:
    name: sisters-app
  mvc:
    servlet:
      path: /rest


---

server:
  port: 8081

spring:
  profiles: dev
# Datasource configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/sisters
    password: pylypchenko
    username: pylypchenko
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: true
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop


#Loggin configurations
logging:
  file: src/main/resources/logs/dev_app.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss}  %highlight(%-5level) %cyan(%-40.40logger{40}) : %msg %n'
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread]  %logger{36} : %msg%n'
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    application.sisters : DEBUG

# Other properties
allowedOrigins: 'http://localhost:4200'
upload.path: /home/pylypchenko/IdeaProjects/sisters-app/sisters/files



---
spring:
  profiles: prod
server:
  port: 8080
