spring:
  profiles:
    active: dev
  application:
    name: sisters-app



# Datasource configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/sisters
    password: pylypchenko
    username: pylypchenko
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop


# Other properties
web.allowed-origins: 'http://localhost:4200'
images.upload-path: '/home/pylypchenko/IdeaProjects/sisters-app/sisters/files'


# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

# Security

security.jwt.token.secret-key: 'sisters-secret'
security.jwt.token.expire-length: 3600000


server:
  servlet:
    context-path: '/api'



---

server:
  port: 8081

spring:
  profiles: dev

# Datasource configuration
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/sisters
    password: pylypchenko
    username: pylypchenko
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: true
      hibernate.use_sql_comments: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.jdbc.fetch_size: 50
      hibernate.jdbc.batch_size: 50
    hibernate:
      ddl-auto: create-drop
    open-in-view: false



#Loggin configurations
logging:
  file: src/main/resources/logs/dev_app.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss}  %highlight(%-5level) %cyan(%-40.40logger{40}) : %msg %n'
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread]  %logger{36} : %msg%n'
  level:
    application.sisters: DEBUG
    org.springframework.web: DEBUG
    org.springframework.controllers: DEBUG

    # logging hibernate
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.hql.ast.AST: INFO
    org.hibernate.tool.hbm2ddl: WARN
    org.hibernate.hql: DEBUG
    org.hibernate.cache: INFO
    org.hibernate.jdbc: DEBUG



---
spring:
  profiles: prod
server:
  port: 8080


#Loggin configurations
logging:
  file: src/main/resources/logs/prod_app.log
  level:
    org.hibernate: INFO
    application.sisters : INFO