spring:
  profiles:
    active: dev
  application:
    name: sisters-app
  mvc:
    servlet:
      path: /rest


---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/sisters
    password: pylypchenko
    username: pylypchenko
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: true
    show-sql: true


server:
  port: 8081

allowedOrigins: 'http://localhost:4200'



---
spring:
  profiles: prod
server:
  port: 8080
